[package]
name = "tur-web"
version = "0.0.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Web frontend for Turing machine simulator"

[dependencies]
tur = { path = "../../" }
action = { path = "../action/" }
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Window", "Document", "Element", "KeyboardEvent", "HtmlSelectElement", "Clipboard"] }
console_error_panic_hook = { version = "0.1", optional = true }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
base64 = "0.22"
yew = { version = "0.21", features = ["csr"] }
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"
gloo-timers = { version = "0.3", features = ["futures"] }
gloo-events = "0.2"
regex = "1.10"
keymap = { version = "1.0.0-rc.3", features = ["wasm"] }

[features]
default = ["console_error_panic_hook"]
