[package]
name = "tur-cli"
version = "0.2.0"
description = "Command-line interface for Turing machine simulator"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "tur-cli"
path = "src/main.rs"

[dependencies]
tur = { path = "../../", version = "0.2.0" }
clap = { version = "4.0", features = ["derive"] }
atty = "0.2.14"
