name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'platforms/**'
      - 'examples/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'platforms/**'
      - 'examples/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: clippy, rustfmt

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --workspace

      - name: Check CLI builds
        run: cargo check --package tur-cli

      - name: Check TUI builds
        run: cargo check --package tur-tui

      - name: Check web builds
        run: cargo check --package tur-web --target wasm32-unknown-unknown
